version: '3'
services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: "fyp-backend"
    image: "fyp-backend"
    env_file: ./backend/.env

# docker-compose up -d --build