"""
helper function for dbpedia/download-raw.py
"""

import requests
from bs4 import BeautifulSoup

def get_data(url):
    """
        returns dictionary generated by parse_page function
        along with additional pages (parsed)
            - 

    """
    out = parse_page(url)
    return out

def parse_page(url):
    """
        scrapes dbpedia page given in url
        returns dictionary representing dbpedia article object
    """
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")

    table = soup.find("table", {"class": "description"})
    out = {}

    for tr in table.find_all("tr"):
        tds = tr.find_all("td")
        if len(tds) == 2:
            k,v = tds
            k = k.find("a").text.strip()

            value = []
            for li in v.find("ul").find_all("li"):
    
                item = None
                try:
                    a = li.find("a")
                    item = {
                        "href": a["href"],
                        "text": a.text.strip()
                    }
                except:
                    item = li.text.strip()

                value.append(item)

            value = value[0] if len(value)==1 else value

            out[k] = value
        
    return out