"""
this file contains all constants used in the application

    - all_countries is a dictionary
    
        key = country name
        value = {
            lat: latitude,
            lon :longitude,
            code: 2 letter country code,
            flag: link to country flag
        }
"""

import pickle

COUNTRIES = pickle.load(open("pickled/constants.sav", "rb"))


COUNTRY_FEATURE_CATEGORIES = [
    {
        "category": "Economic Information",
        "features": [
            "gdp nominal",
            "gdp nominal per capita",
            "gdp ppp",
            "gdp ppp per capita",
            "gini",
            "hdi",
            "GNI per capita (female)",
            "GNI per capita (male)",
            "male to female income ratio",
            "government budget per capita",
            "oil imports",
            "net oil exports",
            "foreign exchange reserves (million USD)",
            "tariff rate",
            "Unemployment rate",
            "Consumer Price Index, All items",
            "Geographical Outreach, Number of Institutions, Other deposit takers",
            "Geographical Outreach, Number of Institutions, Insurance corporations",
            "Use of Financial Services, Number of Borrowers, Commercial banks",
            "Key Indicators, Use of Financial Services, Outstanding loans from commercial banks (% of GDP)",
            "Geographical Outreach, Number of Branches, Excluding Headquarters, Commercial banks",
            "Financial Development Index",
            "Financial Institutions Access Index",
            "Financial Institutions Efficiency Index",
            "Financial Institutions Index",
            "Financial Markets Access Index",
            "Financial Markets Depth Index",
            "Financial Markets Efficiency Index",
            "Financial Markets Index",
            "Financial, Financial Soundness Indicators, Core Set, Deposit Takers, Capital Adequacy, Non-performing Loans Net of Provisions to Capital, Percent",
            "Employment to population ratio, 15+, total (%) (modeled ILO estimate)",
            "GDP per person employed (constant 2017 PPP $)",
            "Net acquisition of financial assets (% of GDP)",
            "Net incurrence of liabilities, total (% of GDP)",
            "Net investment in nonfinancial assets (% of GDP)",
            "Net lending (+) / net borrowing (-) (% of GDP)",
        ]
    },
    {
        "category": "Population Information",
        "features": [
            "population density",
            "population total",
            "age structure (0-14 years)",
            "age structure (15-64 years)",
            "age structure (over 65 years)",
            "number of births (in thousands)",
            "capital population",
            "fertility rate",
            "literacy rate",
            "male literacy rate",
            "female literacy rate",
            "median age",
            "median male age",
            "median female age",
            "labour force",
            "labour force (agriculture)",
            "labour force (industry)",
            "labour force (service)",
            "sex ratio (at birth)",
            "sex ratio (0-14 years)",
            "sex ratio (15-24 years)",
            "sex ratio (25-54 years)",
            "sex ratio (55-64 years)",
            "sex ratio (over 65 years)",
            "sex ratio (total)",
            "Financial Institutions Depth Index",
            "Population density (people per sq. km of land area)",
            "Population in the largest city (% of urban population)"
        ]
    },
    {
        "category": "Mortality Information",
        "features": [
            "intentional homicide rate",
            "intentional homicide rate count",
            "cocaine use",
            "total firearm death rate",
            "firearm death rate by homicide",
            "firearm death rate by suicide",
            "unintentional firearm death rate",
            "undetermined firearm death rate",
            "guns per 100 inhabitants",
            "opiate use",
            "suicide rate",
            "male suicide rate",
            "female suicide rate",
            "suicide rate (male:female ratio)",
            "suicide rate rank",
            "traffic-related death rate (per 100,000 inhabitants per year)",
            "traffic-related death rate (per 100,000 motor vehicles)",
            "traffic-related death rate (total)",
            "dependency ratio (total)",
            "dependency ratio (youth)",
            "dependency ratio (elderly)",
            "potential support ratio",
            "infant mortality rate under 5 (per 1000 lives births)",
            "life expectancy (overall)",
            "life expectancy (female)",
            "life expectancy (male)",
            "maternal mortality rate (per 100,000 live births)",
            "mortality rate (per 1000 people)"
        ]
    },
    {
        "category": "Other Information",
        "features": [
            "traffic-related death rate (per 1 billion vehicle-km)",
            "co2 emissions (tonnes)",
            "natural gas consumption (million m3 per year)",
            "overall mean BMI",
            "female mean BMI",
            "male mean BMI",
            "number of physicians (per 1000 people)",
            "proportion of population using improved sanitation",
            "cigarette consumption (per year per capita)",
            "number of internet hosts",
            "number of internet users",
            "Consumer Prices, period average, percent change",
            "Gross domestic product, constant prices, purchasing power parity, per capita, percent change ",
            "Agricultural land (% of land area)",
            "Agriculture, forestry, and fishing, value added (% of GDP)",
            "Arable land (% of land area)",
            "Arable land (hectares per person)",
            "Crop production index (2004-2006 = 100)",
            "Employment in agriculture, female (% of female employment) (modeled ILO estimate)",
            "Employment in agriculture, male (% of male employment) (modeled ILO estimate)",
            "Fertilizer consumption (kilograms per hectare of arable land)",
            "Food production index (2004-2006 = 100)",
            "Forest area (% of land area)",
            "Forest area (sq. km)",
            "Land area (sq. km)",
            "Livestock production index (2004-2006 = 100)",
            "Permanent cropland (% of land area)",
            "Rural population",
            "Rural population (% of total population)",
            "Surface area (sq. km)",
            "Grants, excluding technical cooperation (BoP, current US$)",
            "Incidence of tuberculosis (per 100,000 people)",
            "Maternal mortality ratio (modeled estimate, per 100,000 live births)",
            "Mortality rate, under-5 (per 1,000 live births)",
            "Net migration",
            "Prevalence of HIV, total (% of population ages 15-49)",
            "Prevalence of stunting, height for age (% of children under 5)",
            "Primary completion rate, total (% of relevant age group)",
            "School enrollment, primary and secondary (gross), gender parity index (GPI)",
            "Technical cooperation grants (BoP, current US$)",
            "Access to electricity (% of population)",
            "CO2 emissions (kt)",
            "CO2 emissions (metric tons per capita)",
            "Ease of doing business index (1=most business-friendly regulations)",
            "Electric power consumption (kWh per capita)",
            "Energy use (kg of oil equivalent per capita)",
            "Land area where elevation is below 5 meters (% of total land area)",
            "Methane emissions (kt of CO2 equivalent)",
            "Nitrous oxide emissions (thousand metric tons of CO2 equivalent)",
            "Population growth (annual %)",
            "Population in urban agglomerations of more than 1 million (% of total population)",
            "Population living in areas where elevation is below 5 meters (% of total population)",
            "Population, total",
            "Prevalence of underweight, weight for age (% of children under 5)",
            "Renewable electricity output (% of total electricity output)",
            "Renewable energy consumption (% of total final energy consumption)",
            "Terrestrial and marine protected areas (% of total territorial area)",
            "Total greenhouse gas emissions (kt of CO2 equivalent)",
            "Urban population",
            "Urban population (% of total population)",
            "Adjusted net savings, including particulate emission damage (% of GNI)",
            "Central government debt, total (% of GDP)",
            "Charges for the use of intellectual property, payments (BoP, current US$)",
            "Charges for the use of intellectual property, receipts (BoP, current US$)",
            "Current account balance (BoP, current US$)",
            "Expense (% of GDP)",
            "Exports of goods and services (% of GDP)",
            "Foreign direct investment, net inflows (BoP, current US$)",
            "GDP (current US$)",
            "GDP growth (annual %)",
            "GDP per capita (current US$)",
            "GDP per capita growth (annual %)",
            "GDP per capita, PPP (current international $)",
            "GNI per capita, Atlas method (current US$)",
            "GNI per capita, PPP (current international $)",
            "GNI, Atlas method (current US$)",
            "GNI, PPP (current international $)",
            "Gross capital formation (% of GDP)",
            "Gross savings (% of GDP)",
            "Imports of goods and services (% of GDP)",
            "Industry (including construction), value added (% of GDP)",
            "Inflation, GDP deflator (annual %)",
            "Inflation, consumer prices (annual %)",
            "PPP conversion factor, GDP (LCU per international $)",
            "Price level ratio of PPP conversion factor (GDP) to market exchange rate",
            "Revenue, excluding grants (% of GDP)",
            "Total reserves (includes gold, current US$)",
            "Children out of school, primary, female",
            "Children out of school, primary, male",
            "Government expenditure on education, total (% of GDP)",
            "Government expenditure on education, total (% of government expenditure)",
            "Government expenditure per student, primary (% of GDP per capita)",
            "Government expenditure per student, secondary (% of GDP per capita)",
            "Government expenditure per student, tertiary (% of GDP per capita)",
            "Gross intake ratio in first grade of primary education, female (% of relevant age group)",
            "Gross intake ratio in first grade of primary education, male (% of relevant age group)",
            "Labor force, female (% of total labor force)",
            "Labor force, total",
            "Literacy rate, adult female (% of females ages 15 and above)",
            "Literacy rate, adult male (% of males ages 15 and above)",
            "Literacy rate, adult total (% of people ages 15 and above)",
            "Literacy rate, youth female (% of females ages 15-24)",
            "Literacy rate, youth male (% of males ages 15-24)",
            "Literacy rate, youth total (% of people ages 15-24)",
            "Persistence to last grade of primary, female (% of cohort)",
            "Persistence to last grade of primary, male (% of cohort)",
            "Population ages 0-14 (% of total population)",
            "Population ages 15-64 (% of total population)",
            "Primary completion rate, female (% of relevant age group)",
            "Primary completion rate, male (% of relevant age group)",
            "Progression to secondary school, female (%)",
            "Progression to secondary school, male (%)",
            "Pupil-teacher ratio, primary",
            "Repeaters, primary, female (% of female enrollment)",
            "Repeaters, primary, male (% of male enrollment)",
            "School enrollment, primary (% gross)",
            "School enrollment, primary (% net)",
            "School enrollment, primary (gross), gender parity index (GPI)",
            "School enrollment, secondary (% gross)",
            "School enrollment, secondary (% net)",
            "School enrollment, tertiary (% gross)",
            "Trained teachers in primary education (% of total teachers)",
            "Unemployment, female (% of female labor force) (modeled ILO estimate)",
            "Unemployment, male (% of male labor force) (modeled ILO estimate)",
            "Unemployment, total (% of total labor force) (modeled ILO estimate)",
            "Alternative and nuclear energy (% of total energy use)",
            "Energy imports, net (% of energy use)",
            "Energy intensity level of primary energy (MJ/$2011 PPP GDP)",
            "Fossil fuel energy consumption (% of total)",
            "Fuel exports (% of merchandise exports)",
            "GDP per unit of energy use (constant 2017 PPP $ per kg of oil equivalent)",
            "Ores and metals exports (% of merchandise exports)",
            "Time required to get electricity (days)",
            "Total natural resources rents (% of GDP)",
            "Bird species, threatened",
            "Fish species, threatened",
            "Mammal species, threatened",
            "PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)",
            "PM2.5 air pollution, population exposed to levels exceeding WHO guideline value (% of total)",
            "Plant species (higher), threatened",
            "Renewable internal freshwater resources per capita (cubic meters)",
            "Renewable internal freshwater resources, total (billion cubic meters)",
            "Automated teller machines (ATMs) (per 100,000 adults)",
            "Bank capital to assets ratio (%)",
            "Bank nonperforming loans to total gross loans (%)",
            "Broad money (% of GDP)",
            "Broad money growth (annual %)",
            "Commercial bank branches (per 100,000 adults)",
            "Deposit interest rate (%)",
            "Depth of credit information index (0=low to 8=high)",
            "Domestic credit to private sector (% of GDP)",
            "Interest rate spread (lending rate minus deposit rate, %)",
            "International migrant stock, total",
            "Lending interest rate (%)",
            "Listed domestic companies, total",
            "Market capitalization of listed domestic companies (% of GDP)",
            "Market capitalization of listed domestic companies (current US$)",
            "Official exchange rate (LCU per US$, period average)",
            "Real interest rate (%)",
            "Risk premium on lending (lending rate minus treasury bill rate, %)",
            "S&P Global Equity Indices (annual % change)",
            "Stocks traded, total value (% of GDP)",
            "Stocks traded, turnover ratio of domestic shares (%)",
            "Strength of legal rights index (0=weak to 12=strong)",
            "Adolescent fertility rate (births per 1,000 women ages 15-19)",
            "Births attended by skilled health staff (% of total)",
            "Contributing family workers, female (% of female employment) (modeled ILO estimate)",
            "Contributing family workers, male (% of male employment) (modeled ILO estimate)",
            "Employment in industry, female (% of female employment) (modeled ILO estimate)",
            "Employment in industry, male (% of male employment) (modeled ILO estimate)",
            "Employment in services, female (% of female employment) (modeled ILO estimate)",
            "Employment in services, male (% of male employment) (modeled ILO estimate)",
            "Fertility rate, total (births per woman)",
            "Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)",
            "Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)",
            "Life expectancy at birth, female (years)",
            "Life expectancy at birth, male (years)",
            "Prevalence of HIV, female (% ages 15-24)",
            "Prevalence of HIV, male (% ages 15-24)",
            "Proportion of seats held by women in national parliaments (%)",
            "Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate)",
            "Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate)",
            "Vulnerable employment, female (% of female employment) (modeled ILO estimate)",
            "Vulnerable employment, male (% of male employment) (modeled ILO estimate)",
            "Wage and salaried workers, female (% of female employment) (modeled ILO estimate)",
            "Wage and salaried workers, male (% of male employment) (modeled ILO estimate)",
            "Age dependency ratio (% of working-age population)",
            "Birth rate, crude (per 1,000 people)",
            "Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",
            "Cause of death, by injury (% of total)",
            "Cause of death, by non-communicable diseases (% of total)",
            "Completeness of death registration with cause-of-death information (%)",
            "Death rate, crude (per 1,000 people)",
            "Diabetes prevalence (% of population ages 20 to 79)",
            "Hospital beds (per 1,000 people)",
            "Immunization, DPT (% of children ages 12-23 months)",
            "Immunization, measles (% of children ages 12-23 months)",
            "Life expectancy at birth, total (years)",
            "Mortality caused by road traffic injury (per 100,000 people)",
            "Mortality rate, infant (per 1,000 live births)",
            "Mortality rate, neonatal (per 1,000 live births)",
            "Population ages 65 and above (% of total population)",
            "Population, female (% of total population)",
            "Prevalence of anemia among children (% of children under 5)",
            "Prevalence of overweight, weight for height (% of children under 5)",
            "Prevalence of severe wasting, weight for height (% of children under 5)",
            "Prevalence of wasting, weight for height (% of children under 5)",
            "Refugee population by country or territory of asylum",
            "Refugee population by country or territory of origin",
            "Specialist surgical workforce (per 100,000 population)",
            "Air transport, registered carrier departures worldwide",
            "Container port traffic (TEU: 20 foot equivalent units)",
            "Fixed broadband subscriptions (per 100 people)",
            "Fixed telephone subscriptions (per 100 people)",
            "Mobile cellular subscriptions (per 100 people)",
            "Secure Internet servers (per 1 million people)",
            "Business extent of disclosure index (0=less disclosure to 10=more disclosure)",
            "High-technology exports (% of manufactured exports)",
            "High-technology exports (current US$)",
            "International tourism, expenditures (% of total imports)",
            "International tourism, receipts (% of total exports)",
            "Lead time to export, median case (days)",
            "Lead time to import, median case (days)",
            "Logistics performance index: Overall (1=low to 5=high)",
            "Merchandise exports (current US$)",
            "Merchandise imports (current US$)",
            "Merchandise trade (% of GDP)",
            "Net barter terms of trade index (2000 = 100)",
            "New businesses registered (number)",
            "Start-up procedures to register a business (number)",
            "Start-up procedures to register a business, female (number)",
            "Start-up procedures to register a business, male (number)",
            "Time required to start a business (days)",
            "Time required to start a business, female (days)",
            "Time required to start a business, male (days)",
            "Total tax and contribution rate (% of profit)",
            "Intentional homicides (per 100,000 people)",
            "Military expenditure (% of GDP)",
            "Military expenditure (% of general government expenditure)",
            "Tax revenue (% of GDP)",
            "Patent applications, nonresidents",
            "Patent applications, residents",
            "Research and development expenditure (% of GDP)",
            "Researchers in R&D (per million people)",
            "Scientific and technical journal articles",
            "Technicians in R&D (per million people)",
            "Trademark applications, direct nonresident",
            "Trademark applications, direct resident",
        ]
    }
]